/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Avaliacao;
import model.bean.Filme;
import model.bean.Usuario;
import model.dao.AvaliacaoDAO;
import model.dao.FilmeDAO;
import model.dao.UsuarioDAO;

// @author carol
 
public final class TelaAvaliacao extends javax.swing.JInternalFrame {
Avaliacao minhaAvaliacao;
    /**
     * Creates new form TelaAvaliacao
     */
    public TelaAvaliacao() {
        initComponents();
        preencherTabela();
        preencherUsuarios();
        preencherFilmes();
    }
    
    public void limpar(){
        txtNota.setText("");
        txtComentario.setText("");
       
    }
    
    public void preencherTabela(){
            DefaultTableModel dtm = (DefaultTableModel) tblAvaliacao.getModel();
            dtm.setRowCount(0);
            AvaliacaoDAO dao = new AvaliacaoDAO();
            
            for(Avaliacao a : dao.read()){
                dtm.addRow(new Object[] {
                    a.getId_avaliacao(),
                    a.getUsuario().getNome(),
                    a.getFilme().getTitulo(),
                    a.getNota(),
                    a.getComentario(),
                    a.getData_criacao()
                });
            }
    }
    
    public void preencherUsuarios(){
        UsuarioDAO dao = new UsuarioDAO();
        for(Usuario u : dao.read()){
            usuarioComboBox.addItem(u);
        }
    }
    public void preencherFilmes(){
        FilmeDAO dao = new FilmeDAO();
        for(Filme f : dao.read()){
            filmeComboBox.addItem(f);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioComboBox = new javax.swing.JComboBox<>();
        filmeComboBox = new javax.swing.JComboBox<>();
        txtNota = new javax.swing.JTextField();
        txtComentario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvaliacao = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(56, 23));
        setPreferredSize(new java.awt.Dimension(638, 587));

        jLabel1.setText("Usuario");

        jLabel2.setText("Filme");

        jLabel3.setText("Nota");

        jLabel4.setText("Comentário");

        usuarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        filmeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filmeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNota)
                            .addComponent(txtComentario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(27, 27, 27)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(usuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(filmeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar)
                    .addComponent(btnLimpar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tblAvaliacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Usuario", "Nome", "Filme", "Nota", "Comentario", "Data"
            }
        ));
        tblAvaliacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAvaliacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAvaliacao);
        if (tblAvaliacao.getColumnModel().getColumnCount() > 0) {
            tblAvaliacao.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?");

        if(opcao == JOptionPane.YES_OPTION){
            AvaliacaoDAO dao = new AvaliacaoDAO();
            dao.destroy(minhaAvaliacao);
        }
        
        limpar();
        preencherTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            // TODO add your handling code here:
            Avaliacao minhaAvaliacao = new Avaliacao();
            Usuario meuUsuario = new Usuario();

            minhaAvaliacao.setNota(Double.parseDouble(txtNota.getText()));
            minhaAvaliacao.setComentario(txtComentario.getText());

           
            minhaAvaliacao.setUsuario((Usuario) usuarioComboBox.getSelectedItem());
            minhaAvaliacao.setFilme((Filme) filmeComboBox.getSelectedItem());

            //instanciar um objeto da classe DAO
            AvaliacaoDAO dao = new AvaliacaoDAO();

            //invocar o metodo create da classe
            dao.create(minhaAvaliacao);
        
            limpar();
            preencherTabela();                      
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            // TODO add your handling code here:
            minhaAvaliacao.setNota(Double.parseDouble(txtNota.getText()));
            minhaAvaliacao.setComentario(txtComentario.getText());
            
            AvaliacaoDAO dao = new AvaliacaoDAO();

            dao.update(minhaAvaliacao);

            limpar();

            preencherTabela();                      

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tblAvaliacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAvaliacaoMouseClicked
    // TODO add your handling code here:
    int linha = tblAvaliacao.getSelectedRow();

    if (linha != -1) {
        // Obtendo o ID da avaliação a partir da tabela
        String id = tblAvaliacao.getValueAt(linha, 0).toString(); 

        AvaliacaoDAO dao = new AvaliacaoDAO();
        minhaAvaliacao = dao.read(Integer.parseInt(id)); 

        // Preenchendo os campos com as informações da avaliação
        txtNota.setText(String.valueOf(minhaAvaliacao.getNota()));
        txtComentario.setText(minhaAvaliacao.getComentario());
        usuarioComboBox.setSelectedItem(minhaAvaliacao.getUsuario());
        filmeComboBox.setSelectedItem(minhaAvaliacao.getFilme());
        }
    }//GEN-LAST:event_tblAvaliacaoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Filme> filmeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAvaliacao;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtNota;
    private javax.swing.JComboBox<Usuario> usuarioComboBox;
    // End of variables declaration//GEN-END:variables
}
