/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Filme;
import model.bean.FilmeGenero;
import model.bean.Genero;
import model.dao.FilmeDAO;
import model.dao.FilmeGeneroDAO;
import model.dao.GeneroDAO;

// @author carol

    public class TelaFilme extends javax.swing.JInternalFrame {
    Filme meuFilme;
    FilmeGenero filmeGenero;
    
    /**
     * Creates new form TelaFilme
     */
    
    public TelaFilme() {
        initComponents();
        preencherTabela();
        preencherGeneros();
    }

    public void limpar(){
        txtTitulo.setText("");
        txtAno.setText("");
        txtClassificacao.setText("");
        txtDuracao.setText("");
        txtSinopse.setText("");
    }
    
    public void preencherTabela(){
            DefaultTableModel dtm = (DefaultTableModel) tabelaFilmes.getModel();
            dtm.setRowCount(0);
            FilmeDAO dao = new FilmeDAO();
            
            for(Filme f : dao.read()){
                StringBuilder generos = new StringBuilder(); //Crio um construtor de string para concatenar os generos
                for (Genero genero : f.getGeneros()) { 
                        if (generos.length() > 0) { //verifica se o stringbuilder ja esta preenchido
                         generos.append(", "); //separo por virgula
                        }
                    generos.append(genero.getDescricao()); //adiciono o genero na stringbuilder
                  }
                
                dtm.addRow(new Object[] {
                    f.getId_filme(),
                    f.getTitulo(),
                    f.getAno(),
                    f.getClassificacao(),
                    f.getDuracao(),
                    f.getSinopse(),
                    generos.toString()
                });
            }
    }
    
    public void preencherGeneros(){
        GeneroDAO dao = new GeneroDAO();
        for(Genero g : dao.read()){
            generoComboBox.addItem(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtClassificacao = new javax.swing.JTextField();
        txtDuracao = new javax.swing.JTextField();
        txtSinopse = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        generoComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFilmes = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(638, 587));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filme"));
        jPanel1.setPreferredSize(new java.awt.Dimension(638, 587));

        jLabel1.setText("Titulo");

        jLabel2.setText("Ano de Lançamento");

        jLabel3.setText("Genero");

        jLabel4.setText("Classificação");

        jLabel5.setText("Duração");

        jLabel6.setText("Sinopse");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        generoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(txtAno)
                            .addComponent(txtClassificacao)
                            .addComponent(txtDuracao)
                            .addComponent(txtSinopse)
                            .addComponent(generoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 283, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar)
                    .addComponent(btnLimpar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabelaFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Filme", "Titulo", "Ano", "Classificacao", "Duracao", "Sinopse", "Generos"
            }
        ));
        tabelaFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFilmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFilmes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            // TODO add your handling code here:
            //Instanciando as classes necessarias.
            Filme meuFilme = new Filme();
            FilmeGenero filmeGenero = new FilmeGenero();
            
            //Pegando os dados dos campos de Texto
            meuFilme.setTitulo(txtTitulo.getText());
            meuFilme.setAno(Integer.parseInt(txtAno.getText()));
            meuFilme.setClassificacao(Double.parseDouble(txtClassificacao.getText())); 
            meuFilme.setDuracao(Integer.parseInt(txtDuracao.getText()));
            meuFilme.setSinopse(txtSinopse.getText());
            
            //instanciar um objeto da classe DAO
            FilmeDAO dao = new FilmeDAO();
            
            //Pegando o Id do filme para usar no create do FilmeGenero
            int idFilmeGerado = dao.create(meuFilme); // Retorna o ID do filme
            
            if (idFilmeGerado == -1) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar filme.");
            return;
            } 
            meuFilme.setId_filme(idFilmeGerado);
            
             // Pegando o objeto selecionado da JComboBox
             Genero generoSelecionado = (Genero) generoComboBox.getSelectedItem();
             
             //No momento q crio um filme com um genero associado, ja coloco também na tabela FilmeGenero
            FilmeGeneroDAO dois = new FilmeGeneroDAO();
            filmeGenero.setId_genero(generoSelecionado); 
            filmeGenero.setId_filme(meuFilme);
            
            dois.create(filmeGenero);
           
            limpar();
            preencherTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void generoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoComboBoxActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            // TODO add your handling code here:
            meuFilme.setTitulo(txtTitulo.getText());
            meuFilme.setAno(Integer.parseInt(txtAno.getText()));
            meuFilme.setClassificacao(Double.parseDouble(txtClassificacao.getText()));
            meuFilme.setDuracao(Integer.parseInt(txtDuracao.getText()));
            meuFilme.setSinopse(txtSinopse.getText());

            // Pegando o objeto selecionado da JComboBox
            Genero generoSelecionado = (Genero) generoComboBox.getSelectedItem();

            //instanciar um objeto da classe DAO
            FilmeDAO dao = new FilmeDAO();
            
            //invocar o metodo create da classe
            dao.update(meuFilme);

            FilmeGeneroDAO dois = new FilmeGeneroDAO();
            FilmeGenero filmeGenero = new FilmeGenero();
            
            filmeGenero.setId_genero(generoSelecionado);
            filmeGenero.setId_filme(meuFilme);
            dois.update(filmeGenero);
    
            limpar();
            preencherTabela();     
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tabelaFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFilmesMouseClicked
        // TODO add your handling code here:
        int linha = tabelaFilmes.getSelectedRow();
        
        if(linha != -1){
            String id = tabelaFilmes.getValueAt(linha, 0).toString(); // toString = converte p uma string
            
            FilmeDAO dao = new FilmeDAO();
            FilmeGeneroDAO filmeGeneroDAO = new FilmeGeneroDAO();
            
            //Construindo um objeto de filme a partir do ID
            meuFilme = dao.read(Integer.parseInt(id));
            
            //Preencher o formulario com as informações do objeto
            txtTitulo.setText(meuFilme.getTitulo());
            txtAno.setText(String.valueOf(meuFilme.getAno()));
            txtClassificacao.setText(String.valueOf(meuFilme.getClassificacao()));
            txtDuracao.setText(String.valueOf(meuFilme.getDuracao()));
            txtSinopse.setText(meuFilme.getSinopse());
            
            // Recupera o relacionamento FilmeGenero pelo ID do filme (pq o genero fica salvo em FilmeGenero)
            FilmeGenero filmeGenero = filmeGeneroDAO.read(meuFilme.getId_filme()); 
        
            Genero generoDoFilme = filmeGenero.getId_genero(); // Objeto Genero que esta associado ao filme
            
                // Seleciona o gênero na JComboBox com base no indice
                for (int i = 0; i < generoComboBox.getItemCount(); i++) {
                    Genero genero = (Genero) generoComboBox.getItemAt(i); // Recupera cada item da JComboBox
                    if (genero.getId_genero() == generoDoFilme.getId_genero()) {
                        generoComboBox.setSelectedIndex(i); // Seleciona o índice correspondente
                    break;
                }
            }
}
        
    }//GEN-LAST:event_tabelaFilmesMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?");
        
        if(opcao == JOptionPane.YES_OPTION){
            FilmeDAO dao = new FilmeDAO();
            dao.destroy(meuFilme);
        }
        limpar();
        preencherTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Genero> generoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFilmes;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtClassificacao;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtSinopse;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
